pool:
  vmImage: "Ubuntu 16.04"
steps:
  - task: DotNetCoreInstaller@0
    displayName: "Use .NET 5"
    inputs:
      version: 5.0.101
      
  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: test
      projects: "**tests/*Tests.csproj"

  - task: DotNetCoreCLI@2
    displayName: "publish"
    inputs:
      command: publish
      arguments: "-r win-x64 --self-contained=true /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true --output $(Build.ArtifactStagingDirectory)"
      projects: '**/*Console.csproj'
      publishWebProjects: false
      zipAfterPublish: true
   
  - task: PublishBuildArtifacts@1
    inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: Adrien.Croquelois.Ocr.exe